contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = true 
canonifyurls = true
baseurl = "/"
theme = "hugo-tufte"
title = "Apkallum"
subtitle = "“What do we want? GRADUAL CHANGE. When do we want it? IN DUE COURSE.”"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  copyrightHolder = ""
  showPoweredBy = false

# -----------------------------------------------------------------------
# Navigation menu 
# -----------------------------------------------------------------------
[[menu.nav]]
  name = "Home"
  weight = -110 
  identifier = "home"
  url = "/"
[[menu.nav]]
  name = "Projects & Essays"
  weight = -100 
  identifier = "projects-and-essays"
  url = "/projects-and-essays"
[[menu.nav]]
  name = "About"
  weight = -90
  identifier = "about"
  url = "/about"
